load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "protocol",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "libhoth_protocol",
    edition = "2024",
    proc_macro_deps = [
        "@libhoth_crates//:zerocopy-derive",
    ],
    deps = [
        "@libhoth_crates//:aligned",
        "@libhoth_crates//:zerocopy",
    ],
)

rust_test(
    name = "protocol_test",
    crate = ":protocol",
    edition = "2024",
)

