load("@rules_rust//rust:defs.bzl", "rust_doc_test", "rust_library", "rust_test")

rust_library(
    name = "types",
    srcs = [
        "lib.rs",
    ],
    crate_name = "pie_rot_hostcmd_types",
    edition = "2024",
    proc_macro_deps = [
        "//third_party:zerocopy_derive",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//aligned",
        "//error",
        "//hex",
        "//third_party:aligned",
        "//third_party:ufmt",
        "//third_party:zerocopy",
    ],
)

rust_test(
    name = "types_test",
    crate = ":types",
    edition = "2024",
)

rust_doc_test(
    name = "types_doctest",
    crate = ":types",
)

rust_library(
    name = "hello",
    srcs = ["hello.rs"],
    crate_name = "pie_rot_hostcmd_types_hello",
    edition = "2024",
    proc_macro_deps = [
        "//third_party:zerocopy_derive",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":types",
        "//third_party:zerocopy",
    ],
)

rust_library(
    name = "channel",
    srcs = ["channel.rs"],
    crate_name = "pie_rot_hostcmd_types_channel",
    edition = "2024",
    proc_macro_deps = [
        "//third_party:zerocopy_derive",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":types",
        "//third_party:zerocopy",
    ],
)

rust_test(
    name = "channel_test",
    crate = ":channel",
    edition = "2024",
    deps = [
        "//third_party:aligned",
    ],
)

rust_library(
    name = "dfu",
    srcs = ["dfu.rs"],
    crate_name = "pie_rot_hostcmd_types_dfu",
    edition = "2024",
    proc_macro_deps = [
        "//third_party:zerocopy_derive",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":types",
        "//third_party:zerocopy",
    ],
)
