
//! Firmware update steps:
//!
//! 1. Host sets [`DfuSessionId::nonce`] to a randomly-generated 64-bit value.
//! 2. Host sets [`DfuSessionId::target`] to [`DfuTarget::EARLGREY_FW_UPDATE`].
//! 3. Host divides a .fwupdate file into N-byte sized chunks (where N is <=
//!    1000 bytes, leaving room for headers in a 1024-byte mailbox).
//! 4. Host sends a [`DfuWriteRequest`] host command with DfuWriteFlags::NEW_SESSION
//!    set, containing the first chunk.
//! 5. For each remaining chunk, the host sends a [`DfuWriteRequest`] without
//!    the NEW_SESSION flag set.
//! 6. Host sends DfuCompleteRequest with DfuCompleteFlags::RESTART
//! 7. Host observes the eRoT restart into the new firmware.
//! 8. When the Host is satisfied with the reliability of the system, it can
//!    make the new firmware permanent by repeating steps 4..6
//!
//! All [`DfuWriteRequest`] and [`DfuCompleteRequest`] host commands must have
//! the same DfuSessionId.
//!
//! The DfuSessionId contains a nonce, which must be randomly generated by the
//! host. The device will check that the nonce is unique for each new session.

use core::mem::offset_of;
use crate::{HostCmdReq, HostCommand};
use zerocopy::{FromBytes, Immutable, IntoBytes, KnownLayout};

// mailbox size is typically 1024 bytes, but 24 bytes of that is the
// host-command header and DfuWriteRequestHeader.
pub const MAX_DFU_WORD_COUNT: usize = 250;

#[derive(FromBytes, Immutable, IntoBytes, KnownLayout, Debug, PartialEq, Eq)]
#[repr(C)]
pub struct DfuWriteRequest {
    pub header: DfuWriteRequestHeader,
    /// An arbitrary-sized chunk of the .fwupdate file (must be multiple of 4
    /// bytes)
    pub data: [u32],
}
impl HostCmdReq for DfuWriteRequest {
    const COMMAND: HostCommand = HostCommand::DFU_WRITE;
    const VERSION: u8 = 0;
    type Response = ();
}

#[derive(FromBytes, Immutable, KnownLayout, IntoBytes, Debug, Clone, Copy, PartialEq, Eq)]
#[repr(C)]
pub struct DfuWriteRequestHeader {
    /// The session ID;  must be the same for all commands.
    pub session_id: DfuSessionId,
    pub flags: DfuWriteFlags,
}
const _: () = {
    assert!(offset_of!(DfuWriteRequestHeader, session_id) == 0);
    assert!(offset_of!(DfuWriteRequestHeader, flags) == 12);
    assert!(core::mem::size_of::<DfuWriteRequestHeader>() == 16);
};

#[derive(FromBytes, Immutable, KnownLayout, IntoBytes, Debug, Clone, Copy, PartialEq, Eq)]
#[repr(C)]
pub struct DfuSessionId {
    /// The nonce should be randomly generated at the start of the session; it
    /// is used to detect simultaneous use of the DFU functionality.
    pub nonce_low: u32,
    pub nonce_high: u32,

    /// The DFU target to use, in case there are multiple DFU targets on the same chip.
    pub target: DfuTarget,
}

impl DfuSessionId {
    pub const fn new(nonce: u64, target: DfuTarget) -> Self {
        Self {
            nonce_low: nonce as u32,
            nonce_high: (nonce >> 32) as u32,
            target,
        }
    }

    pub const fn nonce(&self) -> u64 {
        self.nonce_low as u64 | ((self.nonce_high as u64) << 32)
    }
}

const _: () = {
    assert!(offset_of!(DfuSessionId, nonce_low) == 0);
    assert!(offset_of!(DfuSessionId, nonce_high) == 4);
    assert!(offset_of!(DfuSessionId, target) == 8);
    assert!(core::mem::size_of::<DfuSessionId>() == 12);
};

#[derive(FromBytes, Immutable, KnownLayout, IntoBytes, Debug, Clone, Copy, PartialEq, Eq)]
#[repr(transparent)]
pub struct DfuTarget(pub u32);
impl DfuTarget {
    /// A .fwupdate file targeting the ROM_EXT and application firmware on an earlgrey chip.
    pub const EARLGREY_FW_UPDATE: Self = Self(0x7766_4745); // EGfw
}

#[derive(FromBytes, Immutable, KnownLayout, IntoBytes, Debug, PartialEq, Eq)]
#[repr(C)]
pub struct DfuCompleteRequest {
    pub session_id: DfuSessionId,
    pub flags: DfuCompleteFlags,
}
impl HostCmdReq for DfuCompleteRequest {
    const COMMAND: HostCommand = HostCommand::DFU_COMPLETE;
    const VERSION: u8 = 0;
    type Response = ();
}
const _: () = {
    assert!(offset_of!(DfuCompleteRequest, session_id) == 0);
    assert!(offset_of!(DfuCompleteRequest, flags) == 12);
    assert!(core::mem::size_of::<DfuCompleteRequest>() == 16);
};

#[derive(
    Default, FromBytes, Immutable, KnownLayout, IntoBytes, Debug, Clone, Copy, PartialEq, Eq,
)]
pub struct DfuWriteFlags(pub u32);
impl DfuWriteFlags {
    /// Set if this is the first chunk of a new DFU session.
    pub const NEW_SESSION: Self = Self(1 << 0);

    pub const fn contains(&self, flags: Self) -> bool {
        (self.0 & flags.0) == flags.0
    }
}
impl core::ops::BitOr for DfuWriteFlags {
    type Output = Self;
    fn bitor(self, rhs: Self) -> Self::Output {
        Self(self.0 | rhs.0)
    }
}

#[derive(
    Default, FromBytes, Immutable, KnownLayout, IntoBytes, Debug, Clone, Copy, PartialEq, Eq,
)]
pub struct DfuCompleteFlags(pub u32);
impl DfuCompleteFlags {
    /// Set if we should restart the chip into the new firmware.
    pub const COLD_RESTART: Self = Self(1 << 0);

    /// Set if we should do a warm restart into the new firmware.
    pub const WARM_RESTART: Self = Self(1 << 1);

    pub const fn contains(&self, flags: Self) -> bool {
        (self.0 & flags.0) == flags.0
    }
}
impl core::ops::BitOr for DfuCompleteFlags {
    type Output = Self;
    fn bitor(self, rhs: Self) -> Self::Output {
        Self(self.0 | rhs.0)
    }
}
